# Generated by Django 6.0.1 on 2026-01-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Project',
                'verbose_name_plural': 'Travel Projects',
                'db_table': 'travel_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID from Art Institute of Chicago API')),
                ('title', models.CharField(max_length=500)),
                ('artist_display', models.CharField(blank=True, max_length=500, null=True)),
                ('date_display', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('artwork_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='projects.travelproject')),
            ],
            options={
                'verbose_name': 'Project Place',
                'verbose_name_plural': 'Project Places',
                'db_table': 'project_places',
                'ordering': ['created_at'],
            },
        ),
    ]
